### ISSUE TITLE
npm publish?

### ISSUE THREAD

**Issue by jordansexton** [jpettersson/node-ordered-merge-stream#2]
Thanks for your work on this! Would it be possible to publish an updated version to npm?

**Comment by jpettersson** [comment]
@jordansexton Are you referring to the updated README? That seems to be the only change that was not yet published to npm. I'll make a patch release to get the package to match the repo.

**Comment by jordansexton** [comment]
Oh, I see. I think the version 0.0.0 threw me off of looking deeper at the commit history. Don't worry about it for a readme change!

**Comment by jpettersson** [comment]
@jordansexton Yeah good point. It's been stuck on `0.0.0`. I just bumped it to `1.0.0` and released. The API is definitely not going to change, so it should be communicated by the semantic version. Thanks for noticing!

**Comment by jordaaash** [comment]
Nice! Thanks again.
